trigger:
- master
pool:
  vmImage: 'vs2017-win2016'
steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Azure connection'
    subscriptionId: '642b54b2-923d-4cae-81f1-c848ca6ed09f'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'snrvsvmarm'
    location: 'East US'
    templateLocation: 'Linked artifact'
    csmFile: 'vsvmarm/azuredeploy.json'
    csmParametersFile: 'vsvmarm/azuredeploy.parameters.json'
    overrideParameters: '- _artifactsLocation https://raw.githubusercontent.com/sunkada/AzureRMADO/master/vsvmarm/azuredeploy.json -adminUser surao -adminPassword Passw0rd@123'
    deploymentMode: 'Incremental'
    deploymentName: 'vsvmarm'