trigger:
- master
pool:
  vmImage: 'ubuntu-latest'
steps:

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Snr (642b54b2-923d-4cae-81f1-c848ca6ed09f)'
    subscriptionId: '642b54b2-923d-4cae-81f1-c848ca6ed09f'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'AZRM-RG'
    location: 'East US'
    templateLocation: 'Linked artifact'
    csmFile: 'createwebapp/azuredeploy.json'
    overrideParameters: '-projectName AzureRMADO -linkedTemplateUri https://raw.githubusercontent.com/sunkada/AzureRMADO/master/createwebapp/linkedStorageAccount.json?token=ALO2QNVBWGGLLUQL72VD73TADJWDA'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'
