
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Azure connection'
    subscriptionId: '642b54b2-923d-4cae-81f1-c848ca6ed09f'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'storage-rg'
    location: 'eastus'
    templateLocation: 'Linked artifact'
    csmFile: 'vm/azuredeploy.json'
    csmParametersFile: 'vm/azuredeploy.parameters.json'
    deploymentMode: 'Incremental'
    deploymentName: 'storage'