apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: aks-workshop-manager-roles
  namespace: aks-workshop-dev
rules:
- apiGroups: ["", "apiextensions.k8s.io", "apps", "autoscaling", "batch", "events.k8s.io", "networking.k8s.io", "policy", "rbac.authorization.k8s.io", "scheduling.k8s.io"]
  resources: ["configmaps", "endpoints", "events", "limitranges", "persistentvolumeclaims", "pods", "resourcequotas", "serviceaccounts", "namespaces", "services", "customresourcedefinitions", "daemonsets", "deployments", "replicasets", "statefulsets", "horizontalpodautoscalers", "cronjobs", "jobs", "events", "ingresses", "networkpolicies", "poddisruptionbudgets", "rolebindings", "roles", "priorityclasses"]
  verbs: ["create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"]
- apiGroups: ["metrics.k8s.io"]
  resources: ["nodes", "pods"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: aks-workshop-manager-role-bindings
  namespace: aks-workshop-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: aks-workshop-manager-roles
subjects:
- apiGroup: rbac.authorization.k8s.io
  name: 09ab8656-df95-463c-af83-d1ce8d54830f
  kind: Group
# - apiGroup: rbac.authorization.k8s.io
#   name: <user_id>
#   kind: User